### ISSUE TITLE
can't open with unityhub

### ISSUE THREAD

**Issue by xxhong** [Parrot222/Unity-Water-Shaders#5]
UnityHub:  Not a unity project

**Comment by kartik-scholarlab** [comment]
look at the pull request, just resolved it.

**Comment by Parrot222** [comment]
Since I've only uploaded the asset folder on GitHub, you'll need to create
a project yourself and place the downloaded files into the asset folder of
your project.

houn ***@***.***>於 2024年3月7日 週四，上午1:05寫道：

**Comment by xxhong** [comment]
tks
